# Generated by Django 4.2.5 on 2023-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=18)),
                ("age", models.IntegerField(default=18)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
